CoreMVCProject/CoreProject/Controllers/AdminController.cs
using CoreProject.Models;
using CoreProject.Models.AppModel;
using CoreProject.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreProject.Controllers
{
    [Authorize(Roles = "davidyc, admin")]
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private readonly AppDBContext _context;

        public AdminController(ILogger<AdminController> logger, AppDBContext context)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.Include(x=>x.Roles)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PhoneNumber,Login,Email,Password")] User user)
        {
            var userDB = _context.Users.FirstOrDefault(u => u.Login == user.Login);
            if (userDB != null)
            {
                ModelState.AddModelError("",$"{user.Login} already use another user");
                return View(user);
            }

            if (ModelState.IsValid)
            {
                Role userRole = await _context.Roles.FirstOrDefaultAsync(r => r.Name == "user");
                var addInfo = new UserAdditionalInfo();
                user.UserAdditionalInfo = addInfo;
                if (userRole != null)
                {
                    user.Roles.Add(userRole);
                    userRole.Users.Add(user);
                }
                
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Login,PhoneNumber,DateBorn,Email,Password")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var userDB = _context.Users.FirstOrDefault(u => u.Id == user.Id);
                    userDB.Login = user.Login;
                    userDB.Password = user.Password;
                    userDB.PhoneNumber = user.PhoneNumber;
                    userDB.Email = user.Email;
                    userDB.DateBorn = user.DateBorn;

                    _context.Update(userDB);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> ShowRoles(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roles = _context.Roles.Where(x => x.Id != 1).ToList();

            var user = await _context.Users.Include(u=>u.Roles)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            var userRoles = new List<UserRolesViewModel>();
            foreach (var role in roles)
            {
                userRoles.Add(new UserRolesViewModel()
                {
                    UserID = id,
                    RoleName = role.Name,
                    HasRole = user.Roles.Contains(role)
                });
            }

            return View(userRoles);
        }

        [HttpPost, ActionName("AddRoles")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRoles(int id, string RoleName)
        {
            var user = await _context.Users.Include(r => r.Roles).FirstOrDefaultAsync(x => x.Id == id);
            var role = await _context.Roles.FirstOrDefaultAsync(x => x.Name == RoleName);

            user.Roles.Add(role);
            role.Users.Add(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("ShowRoles", new { id = id });
        }

        [HttpPost, ActionName("RemoveRoles")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveRoles(int id, string RoleName)
        {            
            var user = await _context.Users.Include(r=>r.Roles).FirstOrDefaultAsync(x=>x.Id == id);
            var role = await _context.Roles.FirstOrDefaultAsync(x => x.Name == RoleName);

            user.Roles.Remove(role);
            role.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("ShowRoles", new { id = id });
        }



        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }

    }
}

CoreMVCProject/CoreProject/Controllers/MyProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreProject.Models;
using CoreProject.Models.AppModel;
using Microsoft.AspNetCore.Authorization;

namespace CoreProject.Controllers
{
    [Authorize]
    public class MyProjectsController : Controller
    {
        private readonly AppDBContext _context;

        public MyProjectsController(AppDBContext context)
        {
            _context = context;
        }

        // GET: MyProjects
        public async Task<IActionResult> Index()
        {
            return View(await _context.MyProjects.ToListAsync());
        }

        // GET: MyProjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var myProject = await _context.MyProjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (myProject == null)
            {
                return NotFound();
            }

            return View(myProject);
        }

        [Authorize(Roles = "davidyc")]
        // GET: MyProjects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MyProjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "davidyc")]
        public async Task<IActionResult> Create([Bind("Id,Name,Decription,External,URL")] MyProject myProject)
        {
            if (ModelState.IsValid)
            {
                myProject.CreateDate = DateTime.UtcNow;
                _context.Add(myProject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(myProject);
        }

        [Authorize(Roles = "davidyc")]
        // GET: MyProjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var myProject = await _context.MyProjects.FindAsync(id);
            if (myProject == null)
            {
                return NotFound();
            }
            return View(myProject);
        }

        // POST: MyProjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "davidyc")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Decription,CreateDate,External,URL")] MyProject myProject)
        {
            if (id != myProject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(myProject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MyProjectExists(myProject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(myProject);
        }

        // GET: MyProjects/Delete/5
        [Authorize(Roles = "davidyc")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var myProject = await _context.MyProjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (myProject == null)
            {
                return NotFound();
            }

            return View(myProject);
        }

        // POST: MyProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "davidyc")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var myProject = await _context.MyProjects.FindAsync(id);
            _context.MyProjects.Remove(myProject);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MyProjectExists(int id)
        {
            return _context.MyProjects.Any(e => e.Id == id);
        }
    }
}

CoreMVCProject/CoreProject/Controllers/RolesManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreProject.Models;
using CoreProject.Models.AppModel;
using Microsoft.AspNetCore.Authorization;

namespace CoreProject.Controllers
{
    [Authorize(Roles = "davidyc")]
    public class RolesManageController : Controller
    {
        private readonly AppDBContext _context;

        public RolesManageController(AppDBContext context)
        {
            _context = context;
        }

        // GET: RolesManage
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: RolesManage/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: RolesManage/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RolesManage/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: RolesManage/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: RolesManage/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Role role)
        {
            if (id != role.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: RolesManage/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: RolesManage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.Id == id);
        }
    }
}

CoreMVCProject/CoreProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core Projects</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Core Projects</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About me</a>
                        </li>


                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MyProjects" asp-action="Index">Projects</a>
                            </li>
                        }

                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                        }
                        @if (User.IsInRole("davidyc"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RolesManage" asp-action="Index">Roles Manage</a>
                            </li>
                        }


                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Hello @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-area="" asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CoreProject - <a asp-area="" asp-controller="Home" asp-action="About">About me</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>